{{- if and (.Values.postgresql.enabled) (.Values.postgresqlExtras.passwords.enabled) }}
  {{- range $service_key, $service_val := .Values.postgresqlExtras.passwords.services }}
    {{- if $service_val.enabled }}
      {{- if not $service_val.auth.existingSecret }}
        {{- $secretName := print "cognigy-insights-" $service_val.serviceName "-postgres-password" }}
        {{- if not $service_val.auth.existingSecret }}
          {{- if not (lookup "v1" "Secret" $.Release.Namespace $secretName) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ printf $secretName }}"
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-4"
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  {{- if $service_val.auth.password }}
  password: {{ $service_val.auth.password | b64enc | quote }}
  {{- else }}
  password: {{ (randAlphaNum 24) | b64enc | quote }}
  {{- end }}

          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}