{{- if .Values.serviceNlpOrchestrator.enabled }}
{{- $statefulRabbitMq_secret := include "common.secretName.render" ( dict "existingSecret" $.Values.statefulRabbitMq.auth.existingSecret "defaultSecret" "cognigy-rabbitmq") }}
{{- $statefulRedis_secret := include "common.secretName.render" ( dict "existingSecret" $.Values.statefulRedis.auth.existingSecret "defaultSecret" "cognigy-redis-password") }}
{{- with .Values.serviceNlpOrchestrator }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-nlp-orchestrator
  namespace: {{ $.Release.Namespace | quote }}
spec:
  selector:
    matchLabels:
      app: service-nlp-orchestrator
  replicas: {{ .replicaCount }}
  template:
    metadata:
      annotations:
        checksum/embedding-models: {{ include (print $.Template.BasePath "/configurations/embedding-models.yaml") $ | sha256sum }}
        checksum/locales: {{ include (print $.Template.BasePath "/configurations/locales.yaml") $ | sha256sum }}
        checksum/cognigy-env: {{ include (print $.Template.BasePath "/configurations/cognigy-env.yaml") $ | sha256sum }}
        checksum/rabbitmq: {{ if not (lookup "v1" "Secret" $.Release.Namespace $statefulRabbitMq_secret) }}{{ $statefulRabbitMq_secret | sha256sum }}{{ else }}{{ toYaml (lookup "v1" "Secret" $.Release.Namespace $statefulRabbitMq_secret).data | sha256sum }}{{ end }}
        checksum/redis: {{ if not (lookup "v1" "Secret" $.Release.Namespace $statefulRedis_secret) }}{{ $statefulRedis_secret | sha256sum }}{{ else }}{{ toYaml (lookup "v1" "Secret" $.Release.Namespace $statefulRedis_secret).data | sha256sum }}{{ end }}
      labels:
        app: service-nlp-orchestrator
    spec:
      {{- if .affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .affinity "context" $) | nindent 8 }}
      {{- end }}
      {{- if .nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if .priorityClassName }}
      priorityClassName: {{ .priorityClassName }}
      {{- end }}
      containers:
        - name: service-nlp-orchestrator
          image: {{ include "common.image.render" (dict "global" $.Values.global "image" .image) }}
          resources: {{- toYaml .resources | nindent 12 }}
          ports:
            - name: metrics
              containerPort: 8002
          volumeMounts:
            - name: rabbitmq-connection-string
              mountPath: /var/run/secrets/rabbitmqConnectionString
              subPath: rabbitmqConnectionString
            - name: local
              mountPath: /data/local
            - name: redis-password
              mountPath: /var/run/secrets/redis-password.conf
              subPath: redis-password.conf
            - name: model-config
              mountPath: /models/usev3/config.pbtxt
              subPath: usev3-config
            - name: model-config
              mountPath: /models/usev4/config.pbtxt
              subPath: usev4-config
            - name: model-config
              mountPath: /models/labse/config.pbtxt
              subPath: labse-config
            - name: locales-config
              mountPath: /app/config
              readOnly: true
          startupProbe:
            httpGet:
              path: /health/startup
              port: 8001
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8001
            failureThreshold: 1
            initialDelaySeconds: 120
            periodSeconds: 60
            timeoutSeconds: 60
          envFrom:
            - configMapRef:
                name: cognigy-env
          env:
            - name: LANGUAGES_TO_RUN
              value: ar-AE,bn-IN,da-DK,de-DE,en-US,en-IN,en-GB,en-CA,en-AU,es-ES,fi-FI,fr-FR,ge-GE,hi-IN,it-IT,ja-JP,ko-KR,nl-NL,nn-NO,pl-PL,pt-PT,pt-BR,ru-RU,sv-SE,ta-IN,th-TH,tr-TR,vi-VN,zh-CN
            - name: LOCALES_CONFIG
              value: /app/config/languageCodeMap.json
            {{- if .extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
      volumes:
        - name: rabbitmq-connection-string
          secret:
            secretName: {{ $statefulRabbitMq_secret }}
            items:
              - key: connection-string
                path: rabbitmqConnectionString
        - name: local
          emptyDir: {}
        - name: redis-password
          secret:
            secretName: {{ $statefulRedis_secret }}
        - name: model-config
          configMap:
            name: embedding-model-config
        - name: locales-config
          configMap:
            name: locales-config-file
      {{- include "image.pullSecrets" $ | nindent 6 }}
      securityContext:
        {{- toYaml .securityContext | nindent 8 }}
{{- end }}
{{- end }}