apiVersion: v1
kind: ConfigMap
metadata:
  name: clamav
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    owner-team: boron
data:
# https://github.com/Cisco-Talos/clamav/blob/c389dfa4c3af92b006ada4f7595bbc3e6df3f356/etc/clamd.conf.sample
  clamd.conf: |-
    ###############
    # General
    ###############

    DatabaseDirectory /var/lib/clamav
    TemporaryDirectory /tmp
    LogTime yes
    PidFile /run/clamav/clamd.pid
    LocalSocket /run/clamav/clamd.sock
    Foreground yes

    TCPSocket 3310    
    {{ if .Values.clamd.tcpAddr }}
    {{- printf "TCPAddr %s" .Values.clamd.tcpAddr -}}
    {{end}} 

    ###############
    # Results
    ###############

    DetectPUA yes
    ExcludePUA NetTool
    ExcludePUA PWTool
    AlgorithmicDetection yes
    Bytecode yes

    ###############
    # Scan Types
    ###############

    ScanPE yes
    DisableCertCheck yes
    ScanELF yes
    AlertBrokenExecutables yes
    ScanOLE2 yes
    ScanPDF yes
    ScanSWF yes
    ScanMail yes
    PhishingSignatures yes
    PhishingScanURLs yes
    ScanHTML yes
    ScanArchive yes
    ScanXMLDOCS yes

    ###############
    # Scan config
    ###############

    {{ if .Values.clamd.streamMaxLength }}
    {{- printf "StreamMaxLength %s" .Values.clamd.streamMaxLength -}}
    {{end}}
    {{ if .Values.clamd.maxScanSize }}
    {{- printf "MaxScanSize %s" .Values.clamd.maxScanSize -}}
    {{end}}
    {{ if .Values.clamd.maxFileSize }}
    {{- printf "MaxFileSize %s" .Values.clamd.maxFileSize -}}
    {{end}}
    MaxRecursion 30
    MaxFiles 50000
    MaxEmbeddedPE 40M
    MaxHTMLNormalize 40M
    MaxHTMLNoTags 2M
    MaxScriptNormalize 5M
    MaxZipTypeRcg 1M
    MaxPartitions 128
    MaxIconsPE 200
    PCREMatchLimit 10000
    PCRERecMatchLimit 10000

    Foreground yes
    LeaveTemporaryFiles no

    # https://github.com/Cisco-Talos/clamav/issues/330
    ConcurrentDatabaseReload no

    ExcludePath ^/proc/
    ExcludePath ^/sys/
    ExcludePath ^/host/proc/
    ExcludePath ^/host/sys/

    MaxDirectoryRecursion 64
    FollowDirectorySymlinks no
    FollowFileSymlinks no
    CrossFilesystems no

    AllowAllMatchScan no
    HeuristicAlerts no
    HeuristicScanPrecedence no

# https://github.com/Cisco-Talos/clamav/blob/c389dfa4c3af92b006ada4f7595bbc3e6df3f356/etc/freshclam.conf.sample
  freshclam.conf: |-
    ###############
    # General
    ###############

    DatabaseDirectory /var/lib/clamav
    PidFile /run/clamav/freshclam.pid
    LogSyslog false
    LogTime yes
    Foreground yes

    {{- if .Values.clamd.httpProxyServer }}
    {{ printf "HTTPProxyServer %s" .Values.clamd.httpProxyServer }}
    {{- end }}
    {{- if (and .Values.clamd.httpProxyServer .Values.clamd.httpProxyPort) }}
    {{ printf "HTTPProxyPort %s"  (.Values.clamd.httpProxyPort | quote) }}
    {{- end }}
    {{- if .Values.clamd.httpProxyUsername }}
    {{ printf "HTTPProxyUsername %s" .Values.clamd.httpProxyUsername }}
    {{- end }}
    {{- if .Values.clamd.httpProxyPassword }}
    {{ printf "HTTPProxyPassword %s" .Values.clamd.httpProxyPassword }}
    {{- end }}

    ###############
    # Updates
    ###############

    DatabaseOwner root
    DatabaseMirror db.local.clamav.net
    DatabaseMirror database.clamav.net
    ScriptedUpdates yes
    NotifyClamd /etc/clamav/clamd.conf
    
    # This option enables downloading of bytecode.cvd, which includes additional
    # detection mechanisms and improvements to the ClamAV engine.
    # Default: yes
    Bytecode yes

    # With this option enabled, freshclam will attempt to load new databases into
    # memory to make sure they are properly handled by libclamav before replacing
    # the old ones.
    # Tip: This feature uses a lot of RAM. If your system has limited RAM and you
    # are actively running ClamD or ClamScan during the update, then you may need
    # to set `TestDatabases no`.
    # Default: yes
    TestDatabases yes
    
    # Number of database checks per day.
    # Default: 12 (every two hours)
    Checks 12

    # Timeout in seconds when connecting to database server
    ConnectTimeout 30
    
    # Maximum time in seconds for each download operation. 0 means no timeout.
    ReceiveTimeout 60

    MaxAttempts 3
    CompressLocalDatabase no
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clamav-certs
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    owner-team: boron
data:
# This is the Cisco Talos root public certificate used to sign ClamAV updates and is available at:
# https://github.com/Cisco-Talos/clamav/blob/main/certs/clamav.crt
# It is required from v1.5.0 as mentioned in the ClamAV release notes and issue below:
# https://github.com/Cisco-Talos/clamav/issues/1588
  ClamAV.crt: |-
    -----BEGIN CERTIFICATE-----
    MIIFhTCCA22gAwIBAgIJBJPyuFHF1b7RMA0GCSqGSIb3DQEBDQUAMF8xDjAMBgNV
    BAsTBUFyYm9yMQ4wDAYDVQQKEwVDaXNjbzE9MDsGA1UEAxM0Q2lzY28gU29mdHdh
    cmUgSWRlbnRpdHkgUm9vdCBDQSBSU0EgNDA5NiBTSEE1MTIgMjA5OTAgFw0yNDAx
    MjQxODQ1MjVaGA8yMDk5MDEyNDE4NDUyNVowXzEOMAwGA1UECxMFQXJib3IxDjAM
    BgNVBAoTBUNpc2NvMT0wOwYDVQQDEzRDaXNjbyBTb2Z0d2FyZSBJZGVudGl0eSBS
    b290IENBIFJTQSA0MDk2IFNIQTUxMiAyMDk5MIICIjANBgkqhkiG9w0BAQEFAAOC
    Ag8AMIICCgKCAgEA14hoPbzqZxPr8Wqpq2H+tOib+DkQP80mUP6zAw3uu+eNygd+
    jOBCenO6B7sp1sqCRT8QBQWQxNHVeVfMQN1vjMrqEMNh/eflVtOGy32UbkuQrVzj
    2H+G1PtjeMQKa26LD8XPDUIOpj9rzPdjKFFfz13tm21gNIiVSTI34T5BS5BNEQj1
    b+VQg+0kbANCOOTiTh+H/gxhpXRv8F3VNUrrPxA7a3WF5jhZZoPBns1LuBDW0fQ0
    av6q/uEWtfxMdSNsAxYWVhO90Nx4khOISA1Fs1h1klGsee5XZkLKdUWedZQzbUz1
    f7VPRxX+ddcK0Js2VPvxemMf2WaTbkrEi62y/cOaxqDs2xDTWEXrgOYYEfQ+RoeY
    pbzBCaErqZvCeOgrnXFSHSyyd9+dTOxJuypBH+AWKtmkQMQQ7RQJSkGvrP9NgRxD
    MXb1U4kpVn7kEEhv6telV9E8R635Zm4h/H9FQyc2LrLOuL5UPewMMWt8HqPbs2Xc
    n1kTLvpEDciDJDRvu4XuBsjgQMA0rlt5BHAmZdGO5Dq4+ARWAYrzN9+M0dK+0phT
    T9OOHItIL6wXcIiYLZBJlHfiemCByIcBBEYaRwdt3VP9tTl0F370StI2t1RMDPgt
    xHcsYqN09QG/tWzwr/yNckFhVs/+UGQWslv2/W6eiKge5REUFuxT6i7V6oUCAwEA
    AaNCMEAwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYE
    FLd8Wz4X/JJ6Oi/+znsT0DTPuju8MA0GCSqGSIb3DQEBDQUAA4ICAQCZEut7iqp8
    39u7CHD8zMrvOMmUKtJ7G1MrhkJfdyek8g7ArG74bgcxM3ptwDusdFgKh/mmCj/m
    FU6TNjsufZ9hAyOE16ZtGflkOrRlihPQThDdGCxQjRsLVQa9S0IDkM1v1ZqvIMEc
    PJOj3rhvkIJVjpHc0AZQP/TnaT/7dKD1wFOSNYwzdvE2HKVNA8XbeS9TNpHqYPvE
    2gX6vQ7Pdn9DIF6YOmOuBobmaD1G7WbDz5Kvz5e3FdkzR+K3sGW4Qsr3OLt25dQS
    H+x7X06fihUxhEgRJJp2cPKABSKVR2hoyzKNEbzgtV25gH7lr+EHA6CQYltkVpyM
    4v1+PdX1EGY0+rAO+NsRwa6ndFteofJLh9PbvxHp0jGWnT1KF4lhmEyyka9JKbqT
    yiyGzDsw/YA9NxiAsp/Ex8aYXX1/SeM/kb6dp7tytsHewwflns1jfGqRVyrXQ41x
    CmmSioBvtZiry8BJTa8xIUWEsBL1pTl2RZrPDAw/qD10K2XJfh5HYFSkIppoIO+9
    0wN8TYcXbyY+JnU/g32AvkmA3o8lotK6nbwuf7MAFdtPHMA4F8mPM3jADc1uGu9O
    YweaA1c+P5KEOyr325cgsT04x4oeyvP3c3XMLpDpSgbzhfc9WyLYCf3R3jHlst1A
    KaDwBk2xoE3knxihYjbcRfjaaYdUkWY4mg==
    -----END CERTIFICATE-----