apiVersion: v1
kind: ConfigMap
metadata:
  name: cognigy-env
  namespace: {{ $.Release.Namespace | quote }}
data:
  # DNS names
  FRONTEND_BASE_URL_WITH_PROTOCOL: {{printf "https://%s" .Values.ingress.serviceUi.host | quote}}
  BACKEND_BASE_URL_WITH_PROTOCOL: {{printf "https://%s" .Values.ingress.serviceApi.host | quote}}
  INSIGHTS_BACKEND_BASE_URL_WITH_PROTOCOL: {{printf "https://%s" .Values.ingress.serviceInsightsApi.host | quote}}
  ENDPOINT_BASE_URL_WITH_PROTOCOL: {{printf "https://%s" .Values.ingress.serviceEndpoint.host | quote}}
  RUNTIME_FILE_MANAGER_BASE_URL_WITH_PROTOCOL: {{printf "https://%s" .Values.ingress.serviceRuntimeFileManager.host | quote}}
  WEBCHAT_BASE_URL_WITH_PROTOCOL: {{printf "https://%s" .Values.ingress.serviceWebchat.host | quote}}
  APPS_BASE_URL_WITH_PROTOCOL: {{printf "https://%s" .Values.ingress.serviceAppSessionManager.host | quote}}
  AGENT_ASSIST_WORKSPACE_API_BASE_URL_WITH_PROTOCOL: {{printf "https://%s" .Values.ingress.agentAssistBackend.host | quote}}
  AGENT_ASSIST_WORKSPACE_FRONTEND_URL_WITH_PROTOCOL: {{printf "https://%s" .Values.ingress.agentAssistFrontend.host | quote}}
  {{- if .Values.knowledgeSearch.enabled }}
  FEATURE_ENABLE_KNOWLEDGE_SEARCH: "true"
  {{- end }}
  STATIC_FILES_URL_WITH_PROTOCOL: {{printf "https://%s" .Values.ingress.serviceStaticFiles.host | quote}}
  ODATA_HOSTNAME: {{ .Values.ingress.serviceAnalyticsOdata.host | quote }}
  ODATA_PROTOCOL: "https"
  {{- if and ($.Values.goals.enabled) ($.Values.cubejs.enabled) ($.Values.serviceInsightsResources.enabled) }}
  FEATURE_INSIGHTS_USE_GOALS_DASHBOARD: "true"
  FEATURE_USE_GOALS: "true"
  {{- end }}
  {{- if and ($.Values.cubejs.enabled) ($.Values.pgoperator.enabled) }}
  FEATURE_INSIGHTS_BUSINESS_DASHBOARD_DIRECT_POSTGRESQL: "true"
  {{- end }}
{{- range $key, $value := .Values.cognigyEnv }}
  {{ $key }}: {{ $value | quote }}
{{- end }}