{{- if .Values.statefulRedis.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis
  namespace: {{ $.Release.Namespace | quote }}
data:
  redis.conf: |-
    port 6379

    tcp-backlog 511
    timeout 0
    tcp-keepalive 300

    daemonize no
    supervised no

    pidfile /var/run/redis_6379.pid
    loglevel notice
    # Log to stdout
    logfile ""

    databases 1

    always-show-logo no

    slave-serve-stale-data yes
    slave-read-only yes
    repl-diskless-sync no
    repl-diskless-sync-delay 5
    repl-disable-tcp-nodelay no
    slave-priority 100

    lazyfree-lazy-eviction no
    lazyfree-lazy-expire no
    lazyfree-lazy-server-del no
    slave-lazy-flush no

    appendonly no
    no-appendfsync-on-rewrite no
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb
    aof-load-truncated yes
    aof-use-rdb-preamble no

    lua-time-limit 5000

    slowlog-log-slower-than 10000
    slowlog-max-len 128

    latency-monitor-threshold 0

    notify-keyspace-events ""

    hash-max-ziplist-entries 512
    hash-max-ziplist-value 64
    list-max-ziplist-size -2
    list-compress-depth 0
    set-max-intset-entries 512
    zset-max-ziplist-entries 128
    zset-max-ziplist-value 64
    hll-sparse-max-bytes 3000
    activerehashing yes
    client-output-buffer-limit normal 0 0 0
    client-output-buffer-limit slave 256mb 64mb 60
    client-output-buffer-limit pubsub 32mb 8mb 60
    hz 10
    aof-rewrite-incremental-fsync yes

    maxmemory {{.Values.statefulRedis.conf.maxMemory}}
    maxmemory-policy {{.Values.statefulRedis.conf.maxMemoryPolicy}}

    # We mount the password of Redis in the container via a secret
    include /run/secrets/redis-password.conf
{{- end }}