apiVersion: v2
name: cognigy.ai
description: A Helm chart for Cognigy.AI Enterprise Conversational Automation Platform
type: application
version: 4.66.2
appVersion: "4.66.2"
kubeVersion: ">=v1.19.0-0,<v1.28.0-0"
home: https://cognigy.com
icon: https://www.cognigy.com/hubfs/Cognigy.svg
sources:
  - https://github.com/Cognigy/kubernetes
maintainers:
  - name: SRE Team
    email: sre@cognigy.com

dependencies:
  - name: traefik
    version: "23.1.0"
    repository: "https://helm.traefik.io/traefik"
    condition: traefik.enabled
  - name: weaviate
    version: "16.8.0"
    repository: "https://weaviate.github.io/weaviate-helm"
    condition: knowledgeSearch.enabled
  - name: redis
    version: "17.4.1"
    repository: "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami"
    condition: redisHa.enabled
    alias: redisHa
  - name: redis
    version: "17.4.1"
    repository: "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami"
    condition: redisPersistentHa.enabled
    alias: redisPersistentHa
  - name: postgres-operator
    version: "1.10.1"
    repository: "https://opensource.zalando.com/postgres-operator/charts/postgres-operator"
    condition: pgoperator.enabled
    alias: pgoperator
