apiVersion: v2
name: cognigy.ai
description: A Helm chart for Cognigy.AI Enterprise Conversational Automation Platform
type: application
version: 4.40.0
appVersion: "4.40.0"
kubeVersion: ">=v1.19.0-0,<v1.24.0-0"
home: https://cognigy.com
icon: https://www.cognigy.com/hubfs/Cognigy.svg
sources:
  - https://github.com/Cognigy/kubernetes
maintainers:
  - name: SRE Team
    email: sre@cognigy.com

dependencies:
- name: traefik
  version: "10.19.4"
  repository: "https://helm.traefik.io/traefik"
  condition: traefik.enabled
