apiVersion: v2
name: cognigy.ai
description: A Helm chart for Cognigy.AI Enterprise Conversational Automation Platform
type: application
version: 4.55.1
appVersion: "4.55.1"
kubeVersion: ">=v1.19.0-0,<v1.27.0-0"
home: https://cognigy.com
icon: https://www.cognigy.com/hubfs/Cognigy.svg
sources:
  - https://github.com/Cognigy/kubernetes
maintainers:
  - name: SRE Team
    email: sre@cognigy.com

dependencies:
  - name: traefik
    version: "23.1.0"
    repository: "https://helm.traefik.io/traefik"
    condition: traefik.enabled
  - name: weaviate
    version: "16.1.0"
    repository: "https://weaviate.github.io/weaviate-helm"
    condition: knowledgeSearch.enabled
  - name: postgresql-ha
    version: 11.7.6
    repository: "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami"
    condition: postgresql.enabled
    alias: postgresql
  - name: redis
    version: "17.4.1"
    repository: "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami"
    condition: redis-ha.enabled
    alias: redis-ha
  - name: redis
    version: "17.4.1"
    repository: "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami"
    condition: redis-persistent-ha.enabled
    alias: redis-persistent-ha
