{{- if $.Values.pgoperator.enabled }}
{{- if $.Values.cubejs.dbMigration.enabled }}
{{- $dbMigration_dbSecret := include "cubejs.postgresql.password.existingSecret" $ }}
{{- with .Values.cubejs.dbMigration }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: insights-db-migration-manager
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    "helm.sh/hook": {{ .helmHook.hook | quote }}
    "helm.sh/hook-weight": {{ .helmHook.hookWeight | quote }}
    "helm.sh/hook-delete-policy": {{ .helmHook.deletePolicy | quote }}
spec:
  template:
    metadata:
      name: insights-db-migration-manager
    spec:
      restartPolicy: Never
      {{- if .securityContext }}
      securityContext:
        {{- toYaml .securityContext | nindent 8 }}
      {{- end }}
      {{- if .affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .affinity "context" $) | nindent 8 }}
      {{- end }}
      {{- if .nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if .priorityClassName }}
      priorityClassName: {{ .priorityClassName }}
      {{- end }}
      containers:
        - name: insights-db-migration-manager
          image: {{ include "common.image.render" (dict "global" $.Values.global "image" .image) }}
          resources: {{- toYaml .resources | nindent 12 }}
          env:
            - name: INSIGHTS_POSTGRES_DATA_MIGRATION_MODE
              value: {{ .migration.mode | quote }}
            - name: POSTGRES_HOST
              value: {{ include "common.tplvalues.render" (dict "value" $.Values.cubejs.postgresql.host "context" $) | quote }}
            {{- if $.Values.cubejs.postgresql.readReplica.useReadReplica }}
            - name: INSIGHTS_POSTGRES_DB_REPLICA_HOST
              value: {{ include "common.tplvalues.render" (dict "value" $.Values.cubejs.postgresql.readReplica.host "context" $) | quote }}
            {{- end }}
            - name: POSTGRES_PORT
              value: {{ $.Values.cubejs.postgresql.port | quote }}
            - name: POSTGRES_DB
              value: {{ $.Values.cubejs.postgresql.database | quote }}
            {{- if .migration.include }}
            - name: INSIGHTS_INCLUDE_MIGRATION_NAME
              value: {{ .migration.include | quote }}
            {{- end }}
            {{- if .migration.exclude }}
            - name: INSIGHTS_EXCLUDE_MIGRATION_NAME
              value: {{ .migration.exclude | quote }}
            {{- end }}
            - name: POSTGRES_USER
              value: {{ $.Values.cubejs.postgresql.username | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $dbMigration_dbSecret }}
                  key: password
      {{- include "image.pullSecretsCognigy" $ | nindent 6 }}
{{- end }}
{{- end }}
{{- end }}
