{{- $dataExpiration_dbSecret := include "cubejs.postgresql.password.existingSecret" $ }}
{{- if and (.Values.cubejs.enabled) (.Values.pgoperator.enabled)}}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: insights-data-expiration
  namespace: {{ $.Release.Namespace | quote }}
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      parallelism: 1
      backoffLimit: 3 # Max 3 retries
      template:
        spec:
          securityContext:
            {{- toYaml .Values.cubejs.dataExpiration.securityContext | nindent 12 }}
          restartPolicy: OnFailure
          {{- if .Values.cubejs.dataExpiration.affinity }}
          affinity: {{- include "common.tplvalues.render" (dict "value" .Values.cubejs.dataExpiration.affinity "context" $) | nindent 8 }}
          {{- end }}
          {{- if .Values.cubejs.dataExpiration.nodeSelector }}
          nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.cubejs.dataExpiration.nodeSelector "context" $) | nindent 8 }}
          {{- end }}
          {{- if .Values.cubejs.dataExpiration.tolerations }}
          tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.cubejs.dataExpiration.tolerations "context" $) | nindent 8 }}
          {{- end }}
          containers:
            - name: insights-data-expiration
              image: {{ include "common.image.render" (dict "global" $.Values.global "image" .Values.cubejs.postgresql.image) }}
              command: ["sh", "-c", "psql 'postgresql://'${INSIGHTS_POSTGRES_USER}':'${INSIGHTS_POSTGRES_PASSWORD}'@'${INSIGHTS_POSTGRES_DB_HOST}':'${INSIGHTS_POSTGRES_PORT}'/'${INSIGHTS_POSTGRES_DB}'' -c 'SET timezone = '\''UTC'\''; DELETE FROM public.conversations WHERE \"expiresAt\" < NOW(); DELETE FROM public.sessions WHERE \"expiresAt\" < NOW(); DELETE FROM public.analytics WHERE \"expiresAt\" < NOW(); DELETE FROM public.liveagentescalations WHERE \"expiresAt\" < NOW(); DELETE FROM public.voicegatewayevents WHERE \"expiresAt\" < NOW(); DELETE FROM public.stepevents WHERE \"expiresAt\" < NOW(); '"]
              env:
              - name: INSIGHTS_POSTGRES_DB_HOST
                value: {{ include "common.tplvalues.render" (dict "value" $.Values.cubejs.postgresql.host "context" $) | quote }}
              {{- if $.Values.cubejs.postgresql.readReplica.useReadReplica }}
              - name: INSIGHTS_POSTGRES_DB_REPLICA_HOST
                value: {{ include "common.tplvalues.render" (dict "value" $.Values.cubejs.postgresql.readReplica.host "context" $) | quote }}
              {{- end }}
              - name: INSIGHTS_POSTGRES_DB
                value: {{ $.Values.cubejs.postgresql.database | quote }}
              - name: INSIGHTS_POSTGRES_PORT
                value: {{ $.Values.cubejs.postgresql.port | quote }}
              - name: INSIGHTS_POSTGRES_USER
                value: {{ $.Values.cubejs.postgresql.username | quote }}
              - name: INSIGHTS_POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ $dataExpiration_dbSecret }}
                    key: password
          {{- include "image.pullSecretsCognigy" $ | nindent 10 }}
{{- end }}
