{{- if or (eq .Values.cloud.provider "local-microk8s") (eq .Values.cloud.provider "local-rancher") }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flow-modules
  namespace: {{ $.Release.Namespace | quote }}
spec:
  accessModes:
    - ReadWriteOnce
{{- if eq .Values.cloud.provider "local-microk8s" }}
  storageClassName: "microk8s-hostpath"
{{- else if eq .Values.cloud.provider "local-rancher" }}
  storageClassName: "local-path"
{{- end }}
  resources:
    requests:
      storage: 5Gi
{{ end }}