{{- if or (eq .Values.cloud.provider "local-microk8s") (eq .Values.cloud.provider "local-rancher") }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: functions
  namespace: {{ $.Release.Namespace | quote }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- include "functions.storage.class" $ | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.functions.persistence.size | default "5Gi" }}
{{ end }}