{{- if and (.Values.podMonitors.enabled) (eq (.Values.serviceUsage.metrics.enabled | toString) "true") }}
{{- with .Values.podMonitors }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: prom-cognigy-monitor-cognigy-ai-service-usage
  namespace: {{ .namespace }}
spec:
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
  podMetricsEndpoints:
    - path: /metrics
      port: metrics
  selector:
    matchLabels:
      app: service-usage
{{- end }}
{{- end }}
