{{- if (.Values.podMonitors.enabled) }}
{{- with .Values.podMonitors }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: prom-cognigy-monitor-cognigy-ai-service-ai
  namespace: {{ .namespace }}
spec:
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
  podMetricsEndpoints:
    - path: /metrics
      port: metrics
    {{- if $.Values.sidecarVM4.enabled }}
    - path: /metrics
      port: vm4
    {{- end }}
  selector:
    matchLabels:
      app: service-ai
{{- end }}
{{- end }}