{{- if and (.Values.podMonitors.enabled) (.Values.serviceNlpEmbeddingXx.enabled) }}
{{- with .Values.podMonitors }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: prom-cognigy-monitor-cognigy-ai-service-nlp-embedding-xx
  namespace: {{ .namespace }}
spec:
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
  podMetricsEndpoints:
    - path: /metrics
      port: metrics
  selector:
    matchLabels:
      app: service-nlp-embedding-xx
{{- end }}
{{- end }}