{{- if (not .Values.migrateFS.finished) }}
{{- if and (eq .Values.cloud.provider "azure") (not (.Values.flowModules.persistence.storageClass)) }}
---
kind: StorageClass
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
metadata:
  name: flow-modules
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - cache=strict
parameters:
  skuName: Premium_LRS

{{ end }}
{{ end }}