{{- if eq .Values.cloud.provider "azure" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flow-modules
  namespace: {{ $.Release.Namespace | quote }}
spec:
  accessModes:
    - ReadWriteMany
  {{- include "flowModules.storage.class" $ | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.flowModules.persistence.size | default "100Gi" }}

{{ end }}