{{- if eq .Values.cloud.provider "azure" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: functions
  namespace: {{ $.Release.Namespace | quote }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: functions
  resources:
    requests:
      storage: 100Gi

{{ end }}