{{- if (not .Values.migrateFS.finished) }}
{{- if eq .Values.cloud.provider "azure" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: functions
  namespace: {{ $.Release.Namespace | quote }}
spec:
  accessModes:
    - ReadWriteMany
  {{- include "functions.storage.class" $ | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.functions.persistence.size | default "100Gi" }}

{{ end }}
{{ end }}