{{- if and (eq .Values.cloud.provider "azure") (.Values.weaviate.storage.customStorageClass.enabled) (.Values.weaviate.enabled) (.Values.knowledgeSearch.enabled) }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.weaviate.storage.customStorageClass.azure.storageClassName | quote }}
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    kubernetes.io/cluster-service: "true"
provisioner: {{ .Values.weaviate.storage.customStorageClass.azure.provisionerName | quote }}
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
parameters:
  cachingmode: ReadOnly
  kind: Managed
  storageaccounttype: {{ .Values.weaviate.storage.customStorageClass.azure.azureStorageAccountType | quote }}
{{- end -}}