{{- with .Values.statefulRabbitMq }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: {{ $.Release.Namespace | quote }}
spec:
  selector:
    matchLabels:
      app: rabbitmq
  replicas: {{ .replicaCount }}
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: {{ .image }}
          resources: {{- toYaml .resources | nindent 12 }}
          ports:
          - name: rabbitmq
            containerPort: 5672
          - name: rabbitmq-man
            containerPort: 15672
          - name: metrics
            containerPort: 15692
          env:
          - name: RABBITMQ_DEFAULT_USER
            value: cognigy
          - name: RABBITMQ_DEFAULT_PASS
            valueFrom:
              secretKeyRef:
                name: cognigy-rabbitmq
                key: rabbitmq-password
      imagePullSecrets:
      - name: cognigy-registry-token
{{- end }}