{{- if .Values.statefulRedisPersistent.enabled }}
{{- $statefulRedisPersistent_secret := include "common.secretName.render" ( dict "existingSecret" $.Values.statefulRedisPersistent.auth.existingSecret "defaultSecret" "cognigy-redis-persistent-password") }}
{{- with .Values.statefulRedisPersistent }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-persistent
  namespace: {{ $.Release.Namespace | quote }}
spec:
  selector:
    matchLabels:
      app: redis-persistent
  replicas: {{ .replicaCount }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis-persistent
    spec:
      {{- if .affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .affinity "context" $) | nindent 8 }}
      {{- end }}
      {{- if .nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if .priorityClassName }}
      priorityClassName: {{ .priorityClassName }}
      {{- end }}
      containers:
        - name: redis-persistent
          image: {{ include "common.image.render" (dict "global" $.Values.global "image" .image) }}
          resources: {{- toYaml .resources | nindent 12 }}
          ports:
          - containerPort: 6379
          env:
            {{- if .extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          volumeMounts:
          - name: redis-data
            mountPath: /data
          - name: redis-password-config
            mountPath: /var/run/secrets/
          - name: redis-persistent-config
            mountPath: /var/run/config
      volumes:
        - name: redis-password-config
          secret:
            secretName: {{ $statefulRedisPersistent_secret }}
            items:
            - key: redis-persistent-password.conf
              path: redis-password.conf
        - name: redis-persistent-config
          configMap:
            name: redis-persistent
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-persistent
      {{- include "image.pullSecretsCognigy" $ | nindent 6 }}
      securityContext:
        {{- toYaml .securityContext | nindent 8 }}
{{- end }}
{{- end }}