{{- if .Values.statefulRedisPersistent.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-persistent
  namespace: {{ $.Release.Namespace | quote }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- include "statefulRedisPersistent.storage.class" $ | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.statefulRedisPersistent.persistence.size | default "10Gi" | quote }}
{{- end }}
