apiVersion: v1
kind: Service
metadata:
  name: service-profiles
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app: service-profiles
    owner-team: gold
  annotations:
    {{- if .Values.service.serviceProfiles.annotations }}
      {{- toYaml .Values.service.serviceProfiles.annotations | nindent 4 }}
    {{- end }}
spec:
  ports:
    - name: service-profiles
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: service-profiles
