{{- if .Values.serviceNlpEmbeddingXx.enabled }}
{{- with .Values.serviceNlpEmbeddingXx }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-nlp-embedding-xx
  namespace: {{ $.Release.Namespace | quote }}
spec:
  selector:
    matchLabels:
      app: service-nlp-embedding-xx
  replicas: {{ .replicaCount }}
  template:
    metadata:
      labels:
        app: service-nlp-embedding-xx
    spec:
      {{- if .affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .affinity "context" $) | nindent 8 }}
      {{- end }}
      {{- if .nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .tolerations "context" $) | nindent 8 }}
      {{- end }}
      containers:
        - name: service-nlp-embedding-xx
          image: {{ .image }}
          args:
            - tritonserver
            - '--model-repository=/models'
            - '--model-control-mode=explicit'
            - '--load-model=usev3'
            - '--strict-readiness=true'
            - '--response-cache-byte-size=0'
            - '--log-verbose=1'
            - '--log-info=true'
            - '--log-warning=true'
            - '--log-error=true'
          resources: {{- toYaml .resources | nindent 12 }}
          ports:
            - name: http
              containerPort: 8000
            - name: metrics
              containerPort: 8002
          startupProbe:
            httpGet:
              path: /v2/health/ready
              port: 8000
            failureThreshold: 3
            periodSeconds: 60
          livenessProbe:
            httpGet:
              path: /v2/health/live
              port: 8000
            failureThreshold: 3
            periodSeconds: 60
            timeoutSeconds: 10
            initialDelaySeconds: 90
          volumeMounts:
          - name: model-config
            mountPath: /models/usev3/config.pbtxt
            subPath: usev3-config
      volumes:
        - name: model-config
          configMap:
            name: embedding-model-config
      {{- include "image.pullSecrets" $ | nindent 6 }}
      securityContext:
        {{- toYaml .securityContext | nindent 8 }}
{{- end }}
{{- end }}