{{- if .Values.serviceNlpEmbeddingEn.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: service-nlp-embedding-en
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app: service-nlp-embedding-en
  annotations:
  {{- if .Values.service.serviceNlpEmbeddingEn.annotations }}
    {{- toYaml .Values.service.serviceNlpEmbeddingEn.annotations | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: service-nlp-embedding-en
{{- end }}
