apiVersion: v1
kind: Service
metadata:
  name: service-ui
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app: service-ui
  annotations:
  {{- if .Values.service.serviceUi.annotations }}
    {{- toYaml .Values.service.serviceUi.annotations | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: service-ui
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: service-ui
