apiVersion: v1
kind: Service
metadata:
  name: service-runtime-file-manager
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app: service-runtime-file-manager
  annotations:
  {{- if .Values.service.serviceRuntimeFileManager.annotations }}
    {{- toYaml .Values.service.serviceRuntimeFileManager.annotations | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: service-runtime-file-manager
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: service-runtime-file-manager