apiVersion: v1
kind: Service
metadata:
  name: service-collector
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app: service-collector
  annotations:
    # Annotation to enable plain text http2 (h2c) communication
    traefik.ingress.kubernetes.io/service.serversscheme: h2c
  {{- if .Values.service.serviceCollector.annotations }}
    {{- toYaml .Values.service.serviceCollector.annotations | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: service-collector
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: service-collector
