{{- if .Values.serviceNlpEmbeddingXx.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: service-nlp-embedding-xx
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app: service-nlp-embedding-xx
  annotations:
  {{- if .Values.service.serviceNlpEmbeddingXx.annotations }}
    {{- toYaml .Values.service.serviceNlpEmbeddingXx.annotations | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: service-nlp-embedding-xx
{{- end }}
