apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app: rabbitmq
spec:
  ports:
    - name: rabbitmq
      port: 5672
      targetPort: 5672
      protocol: TCP
    - name: rabbitmq-man
      port: 15672
      targetPort: 15672
      protocol: TCP
    - name: rabbitmq-prometheus
      port: 15692
      protocol: TCP
      targetPort: 15692
  selector:
    app: rabbitmq
