{{- if .Values.statefulRedis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app: redis
  annotations:
  {{- if .Values.service.statefulRedis.annotations }}
    {{- toYaml .Values.service.statefulRedis.annotations | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: redis
{{- end }}
