# We are using the ingress Configuration "agentAsssitBackend" from values.yaml
# as both agent-assist-backend and agent-assist-genesys-notifications-forwarder both share the same host and
# uses the path based routting.
{{- if and (.Values.cognigyAgentAssist.enabled) (.Values.ingress.enabled) }}
{{- if .Values.cognigyAgentAssist.enableGenesysNotificationsForwarder }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: agent-assist-genesys-notifications-forwarder
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    {{- if .Values.tls.enabled }}
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    {{- else }}
    traefik.ingress.kubernetes.io/router.entrypoints: web
    {{- end }}
    {{- if .Values.ingress.agentAssistBackend.ipWhiteListMiddleware.enabled }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ $.Release.Namespace }}-ipwhitelistagentassistbackend@kubernetescrd
    {{- end }}
spec:
  ingressClassName: traefik
  {{- if (.Values.ingress.agentAssistBackend.tls.enabled) }}
  {{- if (.Values.ingress.agentAssistBackend.tls.existingSecret) }}
  tls:
    - secretName: {{ .Values.ingress.agentAssistBackend.tls.existingSecret | quote }}
  {{- else if and (.Values.ingress.agentAssistBackend.tls.crt) (.Values.ingress.agentAssistBackend.tls.key) }}
  tls:
    - secretName: cognigy-agent-assist-backend-tls
  {{- else }}
    {{ required "A valid value for .Values.ingress.agentAssistBackend.tls is required!" .Values.ingress.agentAssistBackend.tls.crt }}
    {{ required "A valid value for .Values.ingress.agentAssistBackend.tls is required!" .Values.ingress.agentAssistBackend.tls.key }}
    {{ required "A valid value for .Values.ingress.agentAssistBackend.tls is required!" .Values.ingress.agentAssistBackend.tls.existingSecret }}
  {{- end }}
  {{- else }}
  {{- include "tlsCertificate.secretName.render" $ | nindent 2 }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.agentAssistBackend.host }}
    http:
      paths:
      - backend:
          service:
            name: agent-assist-genesys-notifications-forwarder
            port:
              number: 8000
        path: /genesys-notifications
        pathType: Prefix
{{- end }}
{{- end }}