{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service-insights-api
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    {{- if .Values.tls.enabled }}
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    {{- else }}
    traefik.ingress.kubernetes.io/router.entrypoints: web
    {{- end }}
    {{- if .Values.ingress.serviceInsightsApi.ipWhiteListMiddleware.enabled }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ $.Release.Namespace }}-ipwhitelistserviceinsightsapi@kubernetescrd
    {{- end }}
spec:
  ingressClassName: traefik
  {{- include "tlsCertificate.secretName.render" $ | nindent 2 }}
  rules:
  - host: {{ .Values.ingress.serviceInsightsApi.host }}
    http:
      paths:
      - backend:
          service:
            name: service-insights-api
            port:
              number: 8000
        path: /
        pathType: Prefix
{{- end }}