# We are using the ingress Configuration "serviceInsightsUI" from values.yaml
# as both service-ui and service-insights-ui both share the same host and
# service-inishgts-ui uses the path based routting.
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service-insights-ui
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    {{- if .Values.tls.enabled }}
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    {{- else }}
    traefik.ingress.kubernetes.io/router.entrypoints: web
    {{- end }}
    {{- if .Values.ingress.serviceUi.ipWhiteListMiddleware.enabled }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ $.Release.Namespace }}-ipwhitelistserviceui@kubernetescrd
    {{- end }}
spec:
  ingressClassName: traefik
  {{- include "tlsCertificate.secretName.render" $ | nindent 2 }}
  rules:
  - host: {{ .Values.ingress.serviceUi.host }}
    http:
      paths:
      - backend:
          service:
            name: service-insights-ui
            port:
              number: 8000
        path: /insights
        pathType: Prefix
{{- end }}