{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service-ui
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      {{- if .Values.ingress.serviceUi.ipWhiteListMiddleware.enabled }}
      traefik.ingress.kubernetes.io/router.middlewares: {{ $.Release.Namespace }}-ipwhitelistserviceui@kubernetescrd
      {{- end }}
spec:
  ingressClassName: traefik
  tls:
  - secretName: cognigy-traefik
  rules:
  - host: {{ .Values.ingress.serviceUi.host }}
    http:
      paths:
      - backend:
          service:
            name: service-ui
            port:
              number: 8000
        path: /
        pathType: Prefix
{{- end }}