{{- if .Values.serviceSessionStateManager.horizontalPodAutoscaler.enabled }}
{{- with .Values.serviceSessionStateManager.horizontalPodAutoscaler }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: service-session-state-manager
  namespace: {{ $.Release.Namespace | quote }}
spec:
  scaleTargetRef:
    kind: Deployment
    name: service-session-state-manager
    apiVersion: apps/v1
  minReplicas: {{ .minReplicas }}
  maxReplicas: {{ .maxReplicas }}
  metrics:
    {{- include "common.tplvalues.render" ( dict "value" .metrics "context" $ ) | nindent 4 }}
  {{- if .behavior }}
  behavior:
    {{- include "common.tplvalues.render" ( dict "value" .behavior "context" $ ) | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
