{{ if not (lookup "v1" "Secret" $.Release.Namespace "cognigy-service-analytics-collector") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cognigy-service-analytics-collector
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    # This is what defines this resource as a hook. Without these lines, the
    # resource is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-4"
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  connection-string: "{{- include "connectionString.mongodb" (dict "pw" (randAlphaNum 24) "serviceName" "service-analytics-collector" "mongodbHosts" .Values.mongodb.hosts) | b64enc }}"
{{- end }}