{{- if and (.Values.serviceUsage.enabled) (not .Values.commonSecrets.billingConsoleApiKey.existingSecret) }}
  {{- if not (lookup "v1" "Secret" $.Release.Namespace "billing-console-secrets") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: billing-console-secrets
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  api-key: {{ .Values.commonSecrets.billingConsoleApiKey.token | b64enc | quote }}
  {{- end }}
{{- end }}
