{{- if and (.Values.knowledgeSearch.enabled) (.Values.weaviate.enabled) (not .Values.commonSecrets.cognigyWeaviateApiKey.existingSecret) }}
{{- if not (lookup "v1" "Secret" $.Release.Namespace "cognigy-weaviate-api-key") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cognigy-weaviate-api-key
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  # use 16 bytes of random value, hex
  AUTHENTICATION_APIKEY_ALLOWED_KEYS: "{{ .Values.commonSecrets.cognigyWeaviateApiKey.token | default (printf "%x" (randAlphaNum 16)) | b64enc }}"
{{- end }}
{{- end }}