---
apiVersion: v1
kind: Secret
metadata:
  name: cognigy-amazon-credentials
  namespace: {{ $.Release.Namespace | quote }}
type: Opaque
data:
  amazon-client-id: {{ .Values.amazonCredentials.clientId | b64enc | quote }}
  amazon-client-secret: {{ .Values.amazonCredentials.clientSecret | b64enc | quote }}
