{{- if .Values.proactiveFollowup.enabled }}
{{- if (not .Values.commonSecrets.cognigyPaiaOauth2Credentials.existingSecret) }}
  {{- if not (lookup "v1" "Secret" $.Release.Namespace "cognigy-paia-oauth2-credentials") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cognigy-paia-oauth2-credentials
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  client-id: {{ .Values.commonSecrets.cognigyPaiaOauth2Credentials.clientId | b64enc | quote }}
  client-secret: {{ .Values.commonSecrets.cognigyPaiaOauth2Credentials.clientSecret | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
