{{- if (not .Values.smtpOAuth2.auth.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cognigy-smtp-oauth2-credentials
  namespace: {{ $.Release.Namespace | quote }}
type: Opaque
data:
  smtp-oauth2-client-id: {{ .Values.smtpOAuth2.auth.clientId | b64enc | quote }}
  smtp-oauth2-client-secret: {{ .Values.smtpOAuth2.auth.clientSecret | b64enc | quote }}
  smtp-oauth2-refresh-token: {{ .Values.smtpOAuth2.auth.refreshToken | b64enc | quote }}
  smtp-oauth2-access-token: {{ .Values.smtpOAuth2.auth.accessToken | b64enc | quote }}
{{- end }}