{{- if (not .Values.smtpPasswordExistingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: cognigy-smtp
  namespace: {{ $.Release.Namespace | quote }}
type: Opaque
data:
  system-smtp-password: {{ .Values.smtpPassword | b64enc | quote }}
{{- end }}