---
apiVersion: v1
kind: Secret
metadata:
  name: cognigy-registry-token
  namespace: {{ $.Release.Namespace | quote }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}