{{- if and .Values.cognigyAgentAssist.enabled (not .Values.cognigyAgentAssist.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: cognigy-agent-assist-credentials
  namespace: {{ $.Release.Namespace | quote }}
type: Opaque
data:
  # this should contain a valid cognigy agent assist access token
  api-access-token: {{ .Values.cognigyAgentAssist.accessToken | b64enc | quote }}
{{- end }}
