{{- if and (.Values.imageCredentials.registry) (.Values.imageCredentials.username) (.Values.imageCredentials.password) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cognigy-registry-token
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    # This is what defines this resource as a hook. Without these lines, the
    # resource is considered part of the release.
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-4"
    "helm.sh/resource-policy": "keep"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}