{{- if and .Values.knowledgeSearch.enabled .Values.knowledgeSearch.gloabalAzureDocumentIntelligenceConfig.enabled (not .Values.knowledgeSearch.gloabalAzureDocumentIntelligenceConfig.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cognigy-azure-ai-document-intelligence-credentials
  namespace: {{ $.Release.Namespace | quote }}
type: Opaque
data:
  azureDocumentIntelligence-api-key: {{ .Values.knowledgeSearch.gloabalAzureDocumentIntelligenceConfig.apiKey | b64enc | quote }}
  azureDocumentIntelligence-endpoint-url: {{ .Values.knowledgeSearch.gloabalAzureDocumentIntelligenceConfig.endpointUrl | b64enc | quote }}
{{- end }}
