{{- if (not .Values.statefulRabbitMq.auth.existingSecret) }}
  {{- if not (lookup "v1" "Secret" $.Release.Namespace "cognigy-rabbitmq") }}
    {{- $rabbitmq_username := .Values.statefulRabbitMq.auth.username | default "cognigy" }}
    {{- $rabbitmq_password := .Values.statefulRabbitMq.auth.password | default (printf "%x" (randAlphaNum 64)) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cognigy-rabbitmq
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  # The RabbitMQ connection string (amqp://user:password@host:port)
  connection-string: "{{ printf "amqp://%s:%s@rabbitmq:5672" $rabbitmq_username $rabbitmq_password | b64enc }}"

  # The RabbitMQ password. Is the same as the password in the connection string
  # but is used by RabbitMQ itself to intialize password protection.
  rabbitmq-password: "{{ $rabbitmq_password | b64enc }}"

  # The connection string to the RabbitMQ API (http(s)://user:password@host:port/api)
  connection-string-api: "{{ printf "http://%s:%s@rabbitmq:15672/api" $rabbitmq_username $rabbitmq_password | b64enc }}"
  {{- end }}
{{- end }}