{{- $redis_persistent_password := printf "%x" (randAlphaNum 64) -}}

{{ if not (lookup "v1" "Secret" $.Release.Namespace "cognigy-redis-persistent-password") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cognigy-redis-persistent-password
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  redis-persistent-password.conf: "{{ printf "requirepass %s" $redis_persistent_password | b64enc }}"
  REDIS_PERSISTENT_PASSWORD: "{{ $redis_persistent_password | b64enc }}"
{{- end }}