{{- if and .Values.platformProvidedLLM.whitelist (eq .Values.platformProvidedLLM.provider "azureOpenAI") (not .Values.platformProvidedLLM.azure.credentials.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: cognigy-platform-provided-llm-credentials
  namespace: {{ $.Release.Namespace | quote }}
type: Opaque
data:
  platform-provided-llm-azure-api-key: {{ .Values.platformProvidedLLM.azure.credentials.apiKey | b64enc | quote }}
{{- end }} 