{{- if (not .Values.cognigyLiveAgent.existingSecret) }}
  {{- if not (lookup "v1" "Secret" $.Release.Namespace "cognigy-live-agent-credentials") }}
apiVersion: v1
kind: Secret
metadata:
  name: cognigy-live-agent-credentials
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  # this should contain a valid cognigy live agent platform token
  cognigy-live-agent-platform-token: {{ .Values.cognigyLiveAgent.platformToken | default (printf "%x" (randAlphaNum 24)) | b64enc | quote }}
  {{- end }}
{{- end }}
