{{- if and (.Values.natsInternal.enabled) (not .Values.natsInternal.natsInternalCredentials.existingSecret) }}
  {{- if not (lookup "v1" "Secret" $.Release.Namespace "cognigy-nats-internal") }}
    {{- $user := .Values.natsInternal.natsInternalCredentials.user | default "cognigy-dev" }}
    {{- $password := .Values.natsInternal.natsInternalCredentials.password | default (printf "%x" (randAlphaNum 64)) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cognigy-nats-internal
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  user: "{{ $user | b64enc }}"

  # The Nats password. Is the same as the password in the connection string
  # but is used by Nats itself to intialize password protection.
  password: "{{ $password | b64enc }}"

{{- end }}
{{- end }}