{{- if and .Values.cognigyAgentAssist.enabled (not .Values.cognigyAgentAssist.existingSecret) }}
  {{- if not (lookup "v1" "Secret" $.Release.Namespace "cognigy-agent-assist-credentials") }}
apiVersion: v1
kind: Secret
metadata:
  name: cognigy-agent-assist-credentials
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  # this should contain a valid cognigy agent assist access token
  api-access-token: {{ .Values.cognigyAgentAssist.accessToken | default (printf "%x" (randAlphaNum 128)) | b64enc | quote }}
  {{- end }}
{{- end }}