{{- if and .Values.knowledgeSearch.enabled .Values.knowledgeSearch.globalAzureDocumentIntelligenceConfig.enabled (not .Values.knowledgeSearch.globalAzureDocumentIntelligenceConfig.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cognigy-azure-ai-document-intelligence-credentials
  namespace: {{ $.Release.Namespace | quote }}
type: Opaque
data:
  azureDocumentIntelligence-api-key: {{ .Values.knowledgeSearch.globalAzureDocumentIntelligenceConfig.apiKey | b64enc | quote }}
  azureDocumentIntelligence-endpoint-url: {{ .Values.knowledgeSearch.globalAzureDocumentIntelligenceConfig.endpointUrl | b64enc | quote }}
{{- end }}
