{{- $redis_password := printf "%x" (randAlphaNum 64) -}}

{{ if not (lookup "v1" "Secret" $.Release.Namespace "cognigy-redis-password") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cognigy-redis-password
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  redis-password.conf: "{{ printf "requirepass %s" $redis_password | b64enc }}"
  REDIS_PASSWORD: "{{ $redis_password | b64enc }}"
{{- end }}