{{- if (not .Values.commonSecrets.niceCXoneKnowledgeHubCredentials.existingSecret) }}
  {{- if not (lookup "v1" "Secret" $.Release.Namespace "cognigy-nice-cxone-knowledgehub-credentials") }}
    {{- if and $.Values.commonSecrets.niceCXoneKnowledgeHubCredentials.clientId $.Values.commonSecrets.niceCXoneKnowledgeHubCredentials.clientSecret}}
---
apiVersion: v1
kind: Secret
metadata:
  name: cognigy-nice-cxone-knowledgehub-credentials
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  client-id: {{ .Values.commonSecrets.niceCXoneKnowledgeHubCredentials.clientId | b64enc | quote }}
  client-secret: {{ .Values.commonSecrets.niceCXoneKnowledgeHubCredentials.clientSecret | b64enc | quote }}
    {{- end }}
  {{- end }}
{{- end }}