{{- if .Values.serviceInsightsForwarder.enabled }}
{{- $statefulRabbitMq_secret := include "common.secretName.render" (dict "existingSecret" $.Values.statefulRabbitMq.auth.existingSecret "defaultSecret" "cognigy-rabbitmq") }}
{{- $redisHa_secret := include "common.secretName.render" (dict "existingSecret" $.Values.redisHa.auth.existingSecret "defaultSecret" "cognigy-redis-password") }}
{{- $serviceInsightsForwarder_dbSecret :=  ternary (include "common.secretName.render" ( dict "existingSecret" (tpl .Values.insights.postgresql.auth.insightsUser.existingSecret .) "defaultSecret" "cognigy-insights-postgres-ha-insights")) (include "cubejs.postgresql.password.existingSecret" $) $.Values.insights.postgresql.usePartitionedTables }}
{{- with .Values.serviceInsightsForwarder }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-insights-forwarder
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    owner-team: gold
spec:
  selector:
    matchLabels:
      app: service-insights-forwarder
  {{- if not (and ($.Values.hpa.enabled) ($.Values.hpa.removeReplicas) ($.Values.hpa.services.serviceInsightsForwarder.enabled)) }}
  replicas: {{ .replicaCount }}
  {{- end }}
  template:
    metadata:
      labels:
        app: service-insights-forwarder
      annotations:
        checksum/cognigy-env: {{ include (print $.Template.BasePath "/configurations/cognigy-env.yaml") $ | sha256sum }}
        checksum/rabbitmq: {{ if not (lookup "v1" "Secret" $.Release.Namespace $statefulRabbitMq_secret) }}{{ $statefulRabbitMq_secret | sha256sum }}{{ else }}{{ toYaml (lookup "v1" "Secret" $.Release.Namespace $statefulRabbitMq_secret).data | sha256sum }}{{ end }}
        checksum/redis: {{ if not (lookup "v1" "Secret" $.Release.Namespace $redisHa_secret) }}{{ $redisHa_secret | sha256sum }}{{ else }}{{ toYaml (lookup "v1" "Secret" $.Release.Namespace $redisHa_secret).data | sha256sum }}{{ end }}
        {{- if $.Values.cognigyCommonPodAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" $.Values.cognigyCommonPodAnnotations "context" $) | nindent 8 }}
        {{- end }}
    spec:
      {{- if .serviceAccountName }}
      serviceAccountName: {{ .serviceAccountName }}
      {{- end }}
      {{- if .affinity }}
      affinity:
        {{- include "common.tplvalues.render" (dict "value" .affinity "context" $) | nindent 8 }}
      {{- end }}
      {{- if or (.nodeSelector) (and ($.Values.hpa.enabled) ($.Values.hpa.useHpaNodeSelector) ($.Values.hpa.services.serviceInsightsForwarder.enabled))}}
      nodeSelector:
        {{- if .nodeSelector }}
        {{- include "common.tplvalues.render" (dict "value" .nodeSelector "context" $) | nindent 8 }}
        {{- end }}
        {{- if and ($.Values.hpa.enabled) ($.Values.hpa.useHpaNodeSelector) ($.Values.hpa.services.serviceInsightsForwarder.enabled) }}
        {{- include "common.tplvalues.render" (dict "value" $.Values.hpa.hpaNodeSelector "context" $) | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- if or (.tolerations) (and ($.Values.hpa.enabled) ($.Values.hpa.useHpaTolerations) ($.Values.hpa.services.serviceInsightsForwarder.enabled))}}
      tolerations:
        {{- if .tolerations }}
        {{- include "common.tplvalues.render" (dict "value" .tolerations "context" $) | nindent 8 }}
        {{- end }}
        {{- if and ($.Values.hpa.enabled) ($.Values.hpa.useHpaTolerations) ($.Values.hpa.services.serviceInsightsForwarder.enabled) }}
        {{- include "common.tplvalues.render" (dict "value" $.Values.hpa.hpaTolerations "context" $) | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- if .priorityClassName }}
      priorityClassName: {{ .priorityClassName }}
      {{- end }}
      containers:
        - name: service-insights-forwarder
          image: {{ include "common.image.render" (dict "global" $.Values.global "image" .image) }}
          resources:
            {{- toYaml .resources | nindent 12 }}
          ports:
            - name: metrics
              containerPort: 8002
          envFrom:
            - configMapRef:
                name: cognigy-env
          env:
            {{- if and ($.Values.pgoperator.enabled) ($.Values.insights.postgresql.usePartitionedTables) ($.Values.pgoperator.postgresqlClusterInsights.enabled) }}
            - name: INSIGHTS_POSTGRES_DB_NAME
              value: {{ $.Values.insights.postgresql.database.name | quote }}
            - name: INSIGHTS_POSTGRES_DB_HOST
              value: {{ include "cognigy-ai.insights.postgresql.cluster.host" $ | quote }}
            - name: INSIGHTS_POSTGRES_DB_PORT
              value: {{ $.Values.insights.postgresql.cluster.port | quote }}
            - name: INSIGHTS_POSTGRES_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ $serviceInsightsForwarder_dbSecret }}
                  key: username
            - name: INSIGHTS_POSTGRES_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $serviceInsightsForwarder_dbSecret }}
                  key: password
            {{- end }}
            {{- if and ($.Values.pgoperator.enabled) ($.Values.cubejs.enabled) (not $.Values.insights.postgresql.usePartitionedTables) ($.Values.pgoperator.postgresqlCluster.enabled) }}
            - name: INSIGHTS_POSTGRES_DB_NAME
              value: {{ $.Values.cubejs.postgresql.database | quote }}
            - name: INSIGHTS_POSTGRES_DB_HOST
              value: {{ include "cognigy-ai.cubejs.postgresql.host" $ | quote }}
            - name: INSIGHTS_POSTGRES_DB_PORT
              value: {{ $.Values.cubejs.postgresql.port | quote }}
            - name: INSIGHTS_POSTGRES_DB_USERNAME
              value: {{ $.Values.cubejs.postgresql.username | quote }}
            - name: INSIGHTS_POSTGRES_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $serviceInsightsForwarder_dbSecret }}
                  key: password
            {{- end }}
            - name: REDIS_ENABLE_RECONNECT
              value: "true"
            - name: RABBITMQ_ENABLE_RECONNECT
              value: "true"
            - name: TRACING_ENABLED
              value: {{ $.Values.tracing.sentry.insights.enabled | quote }}
            - name: TRACING_BASE_URL_WITH_PROTOCOL
              value: {{ $.Values.tracing.sentry.insights.baseUrl | quote }}
            - name: TRACING_ERRORS_ENABLED
              value: {{ $.Values.tracing.sentry.insights.errorsEnabled | quote }}
            - name: TRACING_EVENTS_SAMPLE_RATE
              value: {{ $.Values.tracing.sentry.insights.eventsSampleRate | quote }}
            - name: TRACING_SAMPLE_RATE
              value: {{ $.Values.tracing.sentry.insights.sampleRate | quote }}
            - name: ENVIRONMENT
              value: {{ $.Values.tracing.environment | quote }}
            - name: COGNIGY_AI_RELEASE_VERSION
              value: {{ $.Chart.AppVersion | quote }}
            {{- if $.Values.logRedaction.enabled }}
            - name: LOG_REDACTION_ENABLED
              value: "true"
            {{- end }}
            - name: KAFKA_PUBLISHING_ENABLED
              value: {{ .cxOneParameters.kafkaPublishingEnabled | quote }}
            - name: KAFKA_BROKERS
              value: {{ .cxOneParameters.kafkaBrokers | quote }}
            - name: KAFKA_CLIENT_ID
              value: {{ .cxOneParameters.kafkaClientId | quote }}
            - name: KAFKA_SSL_ENABLED
              value: {{ .cxOneParameters.kafkaSslEnabled | quote }}
            - name: KAFKA_SASL_MECHANISM
              value: {{ .cxOneParameters.kafkaSaslMechanism | quote }}
            - name: KAFKA_CONNECTION_TIMEOUT
              value: {{ .cxOneParameters.kafkaConnectionTimeout | quote }}
            - name: KAFKA_REQUEST_TIMEOUT
              value: {{ .cxOneParameters.kafkaRequestTimeout | quote }}
            - name: KAFKA_RETRY_INITIAL_TIME
              value: {{ .cxOneParameters.kafkaRetryInitialTime | quote }}
            - name: KAFKA_RETRY_RETRIES
              value: {{ .cxOneParameters.kafkaRetryRetries | quote }}
            - name: KAFKA_PRODUCER_ALLOW_AUTO_TOPIC_CREATION
              value: {{ .cxOneParameters.kafkaProducerAllowAutoTopicCreation | quote }}
            - name: KAFKA_PRODUCER_TRANSACTION_TIMEOUT
              value: {{ .cxOneParameters.kafkaProducerTransactionTimeout | quote }}
            - name: KAFKA_PRODUCER_IDEMPOTENT
              value: {{ .cxOneParameters.kafkaProducerIdempotent | quote }}
            - name: KAFKA_PRODUCER_MAX_IN_FLIGHT_REQUESTS
              value: {{ .cxOneParameters.kafkaProducerMaxInFlightRequests | quote }}
            - name: KAFKA_PRODUCER_ACKS
              value: {{ .cxOneParameters.kafkaProducerAcks | quote }}
            - name: KAFKA_TOPIC_SESSIONS
              value: {{ .cxOneParameters.kafkaTopicSessions | quote }}
            - name: KAFKA_SCHEMA_REGISTRY_ENABLED
              value: {{ .cxOneParameters.kafkaSchemaRegistryEnabled | quote }}
            - name: KAFKA_SCHEMA_REGISTRY_URL
              value: {{ .cxOneParameters.kafkaSchemaRegistryUrl | quote }}
            - name: KAFKA_SCHEMA_REGISTRY_AUTO_REGISTER
              value: {{ .cxOneParameters.kafkaSchemaRegistryAutoRegister | quote }}
            - name: KAFKA_SCHEMA_REGISTRY_SCHEMA_VERSION
              value: {{ .cxOneParameters.kafkaSchemaRegistrySchemaVersion | quote }}
            - name: KAFKA_SCHEMA_REGISTRY_REJECT_UNAUTHORIZED
              value: {{ .cxOneParameters.kafkaSchemaRegistryRejectUnauthorized | quote }}
            - name: KAFKA_PROTO_MESSAGE_NAME
              value: {{ .cxOneParameters.kafkaProtoMessageName | quote }}
            - name: KAFKA_PRODUCER_COMPRESSION
              value: {{ .cxOneParameters.kafkaProducerCompression | quote }}
            - name: KAFKA_PRODUCER_BATCH_SIZE
              value: {{ .cxOneParameters.kafkaProducerBatchSize | quote }}
            - name: KAFKA_PRODUCER_LINGER_MS
              value: {{ .cxOneParameters.kafkaProducerLingerMs | quote }}
            - name: CXONE_TRANSFORM_ENABLED
              value: {{ .cxOneParameters.cxOneTransformEnabled | quote }}
            - name: INSIGHTS_SERVICE_FORWARDER_AMQP_PREFETCH_VALUE
              value: {{ .cxOneParameters.insightsServiceForwarderAmqpPrefetchValue | quote }}
            - name: CXONE_SECRETS_ENABLED
              value: {{ .cxOneParameters.kafkaSecretsEnabled | quote }}
            - name: CXONE_SECRET_NAME
              value: {{ .cxOneParameters.kafkaCredentialsSecretName | quote }}
            {{- if .cxOneParameters.roleSessionName }}
            - name: CXONE_ROLE_SESSION_NAME
              value: {{ .cxOneParameters.roleSessionName | quote }}
            {{- end }}
            - name: CXONE_AWS_REGION
              value: {{ $.Values.niceCXOne.awsRegion | quote }}
            - name: CXONE_ROLE_ARN
              value: {{ .cxOneParameters.roleArn | quote }}
            - name: CXONE_ASSUME_ROLE_EXTERNAL_ID
              value: {{ $.Values.niceCXOne.cxoneAssumeRoleExternalId | quote }}
            {{- if $.Values.niceCXOne.sessionDuration }}
            - name: CXONE_SESSION_DURATION
              value: {{ $.Values.niceCXOne.sessionDuration | quote }}
            {{- end }}
            - name: FORWARDER_DEAD_LETTER_ENABLED
              value: {{ .cxOneParameters.deadLetterEnabled | quote }}
            - name: KAFKA_TOPIC_MESSAGE_ANALYTICS
              value: {{ .cxOneParameters.kafkaTopicMessageAnalytics | quote }}
            - name: KAFKA_TOPIC_GOAL_TRACKING
              value: {{ .cxOneParameters.kafkaTopicGoalTracking | quote }}
            - name: KAFKA_TOPIC_GOAL_DEFINITION
              value: {{ .cxOneParameters.kafkaTopicGoalDefinition | quote }}
            - name: KAFKA_TOPIC_GOAL_STEP_DEFINITION
              value: {{ .cxOneParameters.kafkaTopicGoalStepDefinition | quote }}
            - name: CXONE_MESSAGE_ANALYTICS_ENABLED
              value: {{ .cxOneParameters.cxOneMessageAnalyticsEnabled | quote }}
            - name: CXONE_GOAL_TRACKING_ENABLED
              value: {{ .cxOneParameters.cxOneGoalTrackingEnabled | quote }}
            - name: CXONE_GOAL_DEFINITION_ENABLED
              value: {{ .cxOneParameters.cxOneGoalDefinitionEnabled | quote }}
            {{- with .nodeOptions }}
            {{- include "cognigy-ai.common.nodeOptions.render" (dict "value" . "context" $) | nindent 12 }}
            {{- end }}
            {{- if .extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: rabbitmq-connection-string
              mountPath: /var/run/secrets/rabbitmqConnectionString
              subPath: rabbitmqConnectionString
            - name: redis-password
              mountPath: /var/run/secrets/redis-password.conf
              subPath: redis-password.conf
            {{- if .extraVolumeMounts }}
            {{- include "common.tplvalues.render" (dict "value" .extraVolumeMounts "context" $) | nindent 12 }}
            {{- end }}
          startupProbe:
            httpGet:
              path: /health/startup
              port: 8001
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8001
            failureThreshold: 3
            initialDelaySeconds: 90
            periodSeconds: 60
            timeoutSeconds: 10
      volumes:
        - name: rabbitmq-connection-string
          secret:
            secretName: {{ $statefulRabbitMq_secret }}
            items:
              - key: connection-string
                path: rabbitmqConnectionString
        - name: redis-password
          secret:
            secretName: {{ $redisHa_secret }}
        {{- if .extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .extraVolumes "context" $) | nindent 8 }}
        {{- end }}
      {{- include "image.pullSecretsCognigy" $ | nindent 6 }}
      securityContext:
        {{- toYaml .securityContext | nindent 8 }}
{{- end }}
{{- end }}