{{- if .Values.knowledgeSearch.enabled }}
{{- with .Values.taskProcessKnowledgeSourceFile.unstructuredIo }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: unstructured-io
  namespace: {{ $.Release.Namespace | quote }}
spec:
  selector:
    matchLabels:
      app: unstructured-io
  {{- if .replicaCount }}
  replicas: {{ .replicaCount }}
  {{- end }}
  template:
    metadata:
      labels:
        app: unstructured-io
    spec:
      containers:
        - name: unstructured-io
          image: {{ include "common.image.render" (dict "global" $.Values.global "image" .image) }}
          resources: {{- toYaml .resources | nindent 12 }}
          ports:
            - containerPort: 8000
      {{- include "image.pullSecretsCognigy" $ | nindent 6 }}

---
apiVersion: v1
kind: Service
metadata:
  name: unstructured-io
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app: unstructured-io
spec:
  ports:
    - name: unstructured-io
      port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: unstructured-io

{{- end }}
{{- end }}