{{- with .Values.clamd }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clamd
  namespace: {{ $.Release.Namespace | quote }}
spec:
  selector:
    matchLabels:
      app: clamd
  replicas: {{ .replicaCount }}
  template:
    metadata:
      labels:
        app: clamd
      annotations:
        checksum/clamav: {{ include (print $.Template.BasePath "/configurations/clamav.yaml") $ | sha256sum }}
    spec:
      containers:
        - name: clamd          
          image: {{ .image }}
          resources: {{- toYaml .resources | nindent 12 }}
          imagePullPolicy: Always
          ports:
            - containerPort: 3310
          readinessProbe:
            periodSeconds: 3
            tcpSocket:
              port: 3310
          volumeMounts:
            - name: clamav-config
              mountPath: /etc/clamav              
              readOnly: false
      volumes: 
        - name: clamav-config
          configMap:
            name: clamav      
      {{- include "image.pullSecrets" $ | nindent 6 }}
{{- end }}
