apiVersion: v1
kind: Service
metadata:
  name: service-logs
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app: service-logs
    owner-team: gold
  {{- with .Values.service.serviceLogs }}
  {{- if .annotations }}
  annotations:
    {{- toYaml .annotations | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  ports:
    - name: service-logs
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: service-logs
