{{- if .Values.cognigyApps.enabled }}
{{ if not (lookup "v1" "Secret" $.Release.Namespace "cognigy-service-app-session-manager") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cognigy-service-app-session-manager
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    # This is what defines this resource as a hook. Without these lines, the
    # resource is considered part of the release.
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-4"
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  connection-string: "{{- include "connectionString.mongodb" (dict "pw" (randAlphaNum 24) "serviceName" "service-app-session-manager" "mongodbScheme" .Values.mongodb.scheme "mongodbHosts" .Values.mongodb.hosts "mongodbParams" .Values.mongodb.params) | b64enc }}"
{{- end }}
{{- end }}