{{- if .Values.cubejs.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: cube-api-server
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app: cube-api-server
  annotations:
    {{- if .Values.service.cubeApiServer.annotations }}
      {{- toYaml .Values.service.cubeApiServer.annotations | nindent 4 }}
    {{- end }}    
spec:
  ports:
    - name: cube-api-server
      port: 4000
      targetPort: 4000
      protocol: TCP
  selector:
    app: cube-api-server
{{- end }}    