{{- if and (eq .Values.cloud.provider "aws") (.Values.storageClass.aws.enabled) }}
  {{- range $storage_class_key, $storage_class_val := .Values.storageClass.aws.ebs }}
    {{- if kindIs "map" $storage_class_val }}
      {{- if $storage_class_val.enabled }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $storage_class_val.storageClassName | quote }}
provisioner: {{ $storage_class_val.provisionerName | quote }}
allowVolumeExpansion: true
volumeBindingMode: {{ $storage_class_val.volumeBindingMode }}
reclaimPolicy: {{ $storage_class_val.reclaimPolicy }}
parameters:
  type: {{ $storage_class_val.awsEBSVolumeType | quote }}
  fsType: ext4
  encrypted: "true"
  {{- if $storage_class_val.diskIops }}
  iops: {{ $storage_class_val.diskIops | quote }}
  {{- end }}
  {{- if $storage_class_val.diskThroughput }}
  throughput: {{ $storage_class_val.diskThroughput | quote }}
  {{- end }}
      {{- end -}}
    {{- end -}}
  {{- end -}}
{{- end -}}
