{{- if and (eq .Values.cloud.provider "aws") (.Values.weaviate.storage.customStorageClass.enabled) (.Values.weaviate.enabled) (.Values.knowledgeSearch.enabled) }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.weaviate.storage.customStorageClass.aws.storageClassName | quote }}
provisioner: {{ .Values.weaviate.storage.customStorageClass.aws.provisionerName | quote }}
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
parameters:
  type: {{ .Values.weaviate.storage.customStorageClass.aws.awsEBSVolumeType | quote }}
  fsType: ext4
  encrypted: "true"
{{- end -}}
