{{- if and (.Values.cubejs.enabled) (.Values.pgoperator.enabled)}}
{{- if .Values.cubejs.dataCleanup.enabled }}
{{- $dataCleanup_dbSecret := include "cubejs.postgresql.password.existingSecret" $ }}
{{- with .Values.cubejs.dataCleanup }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: insights-data-cleanup-postgres
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    owner-team: gold
spec:
  schedule: {{ .schedule | quote }}
  concurrencyPolicy: {{ .concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      parallelism: {{ .parallelism }}
      backoffLimit: {{ .backoffLimit }}
      activeDeadlineSeconds: {{ .activeDeadlineSeconds }}
      ttlSecondsAfterFinished: {{ .ttlSecondsAfterFinished }}
      template:
        spec:
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          restartPolicy: {{ .restartPolicy }}
          {{- if .affinity }}
          affinity: {{- include "common.tplvalues.render" (dict "value" .affinity "context" $) | nindent 12 }}
          {{- end }}
          {{- if .nodeSelector }}
          nodeSelector: {{- include "common.tplvalues.render" (dict "value" .nodeSelector "context" $) | nindent 12 }}
          {{- end }}
          {{- if .tolerations }}
          tolerations: {{- include "common.tplvalues.render" (dict "value" .tolerations "context" $) | nindent 12 }}
          {{- end }}
          {{- if .priorityClassName }}
          priorityClassName: {{ .priorityClassName }}
          {{- end }}
          containers:
            - name: insights-data-cleanup-postgres
              image: {{ include "common.image.render" (dict "global" $.Values.global "image" $.Values.cubejs.postgresql.image) }}
              resources: {{- toYaml .resources | nindent 16 }}
              command: ["/bin/sh"]
              args: 
              - -c
              - |
                psql 'postgresql://'$INSIGHTS_POSTGRES_USER':'$INSIGHTS_POSTGRES_PASSWORD'@'$INSIGHTS_POSTGRES_DB_HOST':'$INSIGHTS_POSTGRES_PORT'/'$INSIGHTS_POSTGRES_DB'?sslmode='$INSIGHTS_POSTGRES_SSL << 'EOSQL'
                  
                  \echo '--- Starting data cleanup ---'
                  SET timezone = 'UTC';
                  
                  \echo 'Processing table: analytics'
                  DELETE FROM PUBLIC."analytics" A 
                  USING PUBLIC."insightsdeleterequests" B 
                  WHERE A."organisation" = B."organisation" 
                  AND A."projectId" = ANY (B."projectIds") 
                  AND (A."contactId" = ANY (B."contactIds") OR B."contactIds" IS NULL) 
                  AND A."timestamp" <= B."requestedAt" 
                  AND B."entityName" = 'analytics' 
                  AND B."requestedAt" >= NOW() - INTERVAL '6 hours';
                  
                  \echo 'Processing table: sessions'
                  DELETE FROM PUBLIC."sessions" A 
                  USING PUBLIC."insightsdeleterequests" B 
                  WHERE A."organisationId" = B."organisation" 
                  AND A."projectId" = ANY (B."projectIds") 
                  AND (A."userId" = ANY (B."contactIds") OR B."contactIds" IS NULL) 
                  AND A."startedAt" <= B."requestedAt" 
                  AND B."entityName" = 'analytics' 
                  AND B."requestedAt" >= NOW() - INTERVAL '6 hours';
                  
                  \echo 'Processing table: conversations'
                  DELETE FROM PUBLIC."conversations" A 
                  USING PUBLIC."insightsdeleterequests" B 
                  WHERE A."organisation" = B."organisation" 
                  AND A."projectId" = ANY (B."projectIds") 
                  AND (A."contactId" = ANY (B."contactIds") OR B."contactIds" IS NULL) 
                  AND A."timestamp" <= B."requestedAt" 
                  AND B."entityName" = 'conversations' 
                  AND B."requestedAt" >= NOW() - INTERVAL '6 hours';
                  
                  \echo 'Checking for table: conversations_v2'
                  DELETE FROM PUBLIC."conversations_v2" A 
                  USING PUBLIC."insightsdeleterequests" B 
                  WHERE EXISTS (SELECT 1 FROM information_schema.tables 
                                WHERE table_schema = 'public' AND table_name = 'conversations_v2')
                  AND A."organisation" = B."organisation" 
                  AND A."projectId" = ANY (B."projectIds") 
                  AND (A."contactId" = ANY (B."contactIds") OR B."contactIds" IS NULL) 
                  AND A."timestamp" <= B."requestedAt" 
                  AND B."entityName" = 'conversations' 
                  AND B."requestedAt" >= NOW() - INTERVAL '6 hours';
                  
                  \echo 'Checking for table: liveagentescalations'
                  DELETE FROM PUBLIC."liveagentescalations" A 
                  USING PUBLIC."insightsdeleterequests" B 
                  WHERE EXISTS (SELECT 1 FROM information_schema.tables 
                                WHERE table_schema = 'public' AND table_name = 'liveagentescalations')
                  AND A."organisationId" = B."organisation" 
                  AND A."projectId" = ANY (B."projectIds") 
                  AND (A."contactId" = ANY (B."contactIds") OR B."contactIds" IS NULL) 
                  AND A."timestamp" <= B."requestedAt" 
                  AND B."entityName" = 'analytics' 
                  AND B."requestedAt" >= NOW() - INTERVAL '6 hours';
                  
                  \echo 'Checking for table: voicegatewayevents'
                  DELETE FROM PUBLIC."voicegatewayevents" A 
                  USING PUBLIC."insightsdeleterequests" B 
                  WHERE EXISTS (SELECT 1 FROM information_schema.tables 
                                WHERE table_schema = 'public' AND table_name = 'voicegatewayevents')
                  AND A."organisationId" = B."organisation" 
                  AND A."projectId" = ANY (B."projectIds") 
                  AND (A."userId" = ANY (B."contactIds") OR B."contactIds" IS NULL) 
                  AND A."timestamp" <= B."requestedAt" 
                  AND B."entityName" = 'analytics' 
                  AND B."requestedAt" >= NOW() - INTERVAL '6 hours';
                  
                  \echo 'Processing table: stepevents'
                  DELETE FROM PUBLIC."stepevents" A 
                  USING PUBLIC."insightsdeleterequests" B 
                  WHERE A."organisationId" = B."organisation" 
                  AND A."projectId" = ANY (B."projectIds") 
                  AND (A."userId" = ANY (B."contactIds") OR B."contactIds" IS NULL) 
                  AND A."timestamp" <= B."requestedAt" 
                  AND B."entityName" = 'analytics' 
                  AND B."requestedAt" >= NOW() - INTERVAL '6 hours';
                  
                  \echo '--- Data cleanup completed ---'
                EOSQL
              env:
              - name: INSIGHTS_POSTGRES_DB_HOST
                value: {{ include "common.tplvalues.render" (dict "value" $.Values.cubejs.postgresql.host "context" $) | quote }}
              {{- if $.Values.cubejs.postgresql.readReplica.useReadReplica }}
              - name: INSIGHTS_POSTGRES_DB_REPLICA_HOST
                value: {{ include "common.tplvalues.render" (dict "value" $.Values.cubejs.postgresql.readReplica.host "context" $) | quote }}
              {{- end }}
              - name: INSIGHTS_POSTGRES_DB
                value: {{ $.Values.cubejs.postgresql.database | quote }}
              - name: INSIGHTS_POSTGRES_SSL
                value: {{ $.Values.cubejs.postgresql.sslmode | quote }}
              - name: INSIGHTS_POSTGRES_PORT
                value: {{ $.Values.cubejs.postgresql.port | quote }}
              - name: INSIGHTS_POSTGRES_USER
                value: {{ $.Values.cubejs.postgresql.username | quote }}
              - name: INSIGHTS_POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ $dataCleanup_dbSecret }}
                    key: password
          {{- include "image.pullSecretsCognigy" $ | nindent 10 }}
{{- end }}
{{- end }}
{{- end }}