{{- if .Values.knowledgeSearch.enabled }}
{{- if .Values.knowledgeSearch.localCluster }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weaviate
  namespace: cognigy-ai
spec:
  selector:
    matchLabels:
      app: weaviate
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: weaviate
    spec:
      containers:
      - name: weaviate
        image: semitechnologies/weaviate:1.18.0
        args:
          - '--host'
          - '0.0.0.0'
          - '--port'
          - '8080'
          - '--scheme'
          - 'http'
        env:
          - name: QUERY_DEFAULTS_LIMIT
            value: '25'
          - name: AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED
            value: 'true'
          - name: PERSISTENCE_DATA_PATH
            value: '/var/lib/weaviate'
          - name: DEFAULT_VECTORIZER_MODULE
            value: 'none'
          - name: ENABLE_MODULES
            value: ''
          - name: CLUSTER_HOSTNAME
            value: 'node1'
        resources:
          requests:
            cpu: '0.5'
            memory: '1.5Gi'
          limits:
            cpu: '1'
            memory: '2Gi'
        ports:
        - name: http
          containerPort: 8080
        startupProbe:
          httpGet:
            path: /v1/.well-known/ready
            port: 8080
        livenessProbe:
          httpGet:
            path: /v1/.well-known/live
            port: 8080
          failureThreshold: 3
          initialDelaySeconds: 90
          periodSeconds: 60
          timeoutSeconds: 10
      {{- include "image.pullSecrets" $ | nindent 6 }}
      securityContext:
        {{- toYaml .securityContext | nindent 8 }}
{{- end }}
{{- end }}