{{- if .Values.hpa.enabled }}
  {{- range $hpa_key, $hpa_val := .Values.hpa.services }}
    {{- if kindIs "map" $hpa_val }}
      {{- if and ($hpa_val.enabled) (not $hpa_val.keda.enabled) }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $hpa_val.name | quote }}
  namespace: {{ $.Release.Namespace | quote }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $hpa_val.name | quote }}
  minReplicas: {{ $hpa_val.minReplicas }}
  maxReplicas: {{ $hpa_val.maxReplicas }}
  metrics:
    {{- include "common.tplvalues.render" ( dict "value" $hpa_val.metrics "context" $ ) | nindent 4 }}
  {{- if $hpa_val.behavior }}
  behavior:
    {{- include "common.tplvalues.render" ( dict "value" $hpa_val.behavior "context" $ ) | nindent 4 }}
  {{- end }}
      {{- end }}
{{- if and ($hpa_val.enabled) ($hpa_val.keda.enabled) }}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ $hpa_val.name | quote }}
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    scaledobject.keda.sh/transfer-hpa-ownership: "true"
spec:
  scaleTargetRef:
    name: {{ $hpa_val.name | quote }}
  minReplicaCount: {{ $hpa_val.minReplicas }}
  maxReplicaCount: {{ $hpa_val.maxReplicas }}
  triggers:
    {{- include "common.tplvalues.render" ( dict "value" $hpa_val.keda.triggers "context" $ ) | nindent 4 }}
  advanced:
    horizontalPodAutoscalerConfig:
      name: {{ $hpa_val.name | quote }}
      {{- if $hpa_val.behavior }}
      behavior:
        {{- include "common.tplvalues.render" ( dict "value" $hpa_val.behavior "context" $ ) | nindent 8 }}
      {{- end }}
{{- end }}
    {{- end }}
  {{- end }}
{{- end }}