#
# Centralised Auth-Gateway which integrates with Traefik through forward-middleware.
#
# To learn more about the centralised auth-gateway, please refer to:
# https://cognigy.visualstudio.com/Cognigy.AI/_git/cognigy?path=/services/service-api/src/authGateway/README.md&_a=preview
#
# Automatically generate keypair if not provided (GitOps compatible)
#
{{- if .Values.commonSecrets.authGatewayKeyPair.generate }}
{{- if and (not .Values.commonSecrets.authGatewayKeyPair.existingPrivateKeySecret) (not .Values.commonSecrets.authGatewayKeyPair.existingPublicKeySecret) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-gateway-keygen
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: auth-gateway-keygen
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: auth-gateway-keygen
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: auth-gateway-keygen
subjects:
- kind: ServiceAccount
  name: auth-gateway-keygen
  namespace: {{ $.Release.Namespace | quote }}
---
{{- with .Values.serviceApi.authGatewayKeyGenerationJob }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "auth-gateway-keygen-{{ $.Release.Revision }}"
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  backoffLimit: 3
  template:
    metadata:
      name: auth-gateway-keygen
    spec:
      restartPolicy: Never
      {{- if .securityContext }}
      securityContext:
        {{- toYaml .securityContext | nindent 8 }}
      {{- end }}
      {{- if .affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .affinity "context" $) | nindent 8 }}
      {{- end }}
      {{- if .nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if .priorityClassName }}
      priorityClassName: {{ .priorityClassName }}
      {{- end }}
      serviceAccountName: auth-gateway-keygen
      {{- include "image.pullSecretsCognigy" $ | nindent 6 }}
      containers:
      - name: keygen
        image: {{ include "common.image.render" (dict "global" $.Values.global "image" .image) }}
        command:
        - /bin/bash
        - -c
        - |
          set -euo pipefail
          
          # Check if secrets already exist
          if kubectl get secret auth-gateway-private-key -n {{ $.Release.Namespace }} 2>/dev/null; then
            echo "Secrets already exist, skipping generation"
            exit 0
          fi
          
          # Generate keypair
          PRIV_OUT="/tmp/es256-private.pem"
          PUB_OUT="/tmp/es256-public.pem"
          
          tmp_ec_priv="$(mktemp)"
          openssl ecparam -name prime256v1 -genkey -noout -out "${tmp_ec_priv}"
          openssl pkcs8 -topk8 -nocrypt -in "${tmp_ec_priv}" -out "${PRIV_OUT}"
          openssl pkey -in "${PRIV_OUT}" -pubout -out "${PUB_OUT}"
          rm -f "${tmp_ec_priv}"
          
          # Create secrets
          kubectl create secret generic auth-gateway-private-key \
            --from-file=internal-auth-gateway-jwt-private-key.pem="${PRIV_OUT}" \
            --namespace={{ $.Release.Namespace }} \
            --dry-run=client -o yaml | \
            kubectl apply -f -
          
          kubectl create secret generic auth-gateway-public-key \
            --from-file=internal-auth-gateway-jwt-public-key.pem="${PUB_OUT}" \
            --namespace={{ $.Release.Namespace }} \
            --dry-run=client -o yaml | \
            kubectl apply -f -
          
          # Add keep annotation
          kubectl annotate secret auth-gateway-private-key helm.sh/resource-policy=keep -n {{ $.Release.Namespace }} --overwrite
          kubectl annotate secret auth-gateway-public-key helm.sh/resource-policy=keep -n {{ $.Release.Namespace }} --overwrite
          
          echo "Keypair generated and secrets created successfully"
{{- end }}
{{- end }}
{{- end }}