{{- if .Values.ingress.enabled }}
  {{- range $ingress_key, $ingress_val := .Values.ingress }}
    {{- if kindIs "map" $ingress_val }}
      {{- if hasKey $ingress_val "headersMiddleware" }}
        {{- if $ingress_val.headersMiddleware.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ printf "headers%s" (lower $ingress_key)}}
  namespace: {{ $.Release.Namespace | quote }}
spec:
  headers: {{- toYaml $ingress_val.headersMiddleware.headers | nindent 4 }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
