{{- if and (.Values.ingress.enabled) (.Values.ingress.serviceRuntimeFileManager.ipWhiteListMiddleware.enabled) }}
{{- with .Values.ingress.serviceRuntimeFileManager.ipWhiteListMiddleware }}
---
# Whitelisting Based on `X-Forwarded-For` with `depth=0`
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: ipwhitelistserviceruntimefilemanager
  namespace: {{ $.Release.Namespace | quote }}
spec:
  ipWhiteList: {{- toYaml .ipWhiteList | nindent 4 }}
{{- end }}
{{- end }}