{{- if and (.Values.managementUi.enabled) (.Values.managementUi.ingress.ipWhiteListMiddleware.enabled) }}
{{- with .Values.managementUi.ingress.ipWhiteListMiddleware }}
---
# Whitelisting Based on `X-Forwarded-For` with `depth=0`
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ipwhitelistmanagementui
  namespace: {{ $.Release.Namespace | quote }}
spec:
  ipAllowList: {{- toYaml .ipWhiteList | nindent 4 }}
{{- end }}
{{- end }}