{{- if .Values.cubejs.enabled }}
  {{- if .Values.cubejs.persistence.enabled }}
    {{- if (has .Values.cloud.provider (list "aws" "azure" "local-microk8s" "local-rancher")) }} 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cubejs-cubestore-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    owner-team: gold
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.cubejs.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.cubejs.persistence.size | default "10Gi" | quote }}
    {{- end }}
  {{- end }}
{{- end }}
