apiVersion: v1
kind: Service
metadata:
  name: service-analytics-odata
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    app: service-analytics-odata
  annotations:
  {{- if .Values.service.serviceAnalyticsOdata.annotations }}
    {{- toYaml .Values.service.serviceAnalyticsOdata.annotations | nindent 4 }}
  {{- end }}

spec:
  ports:
    - name: service-analytics-odata
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: service-analytics-odata
