{{- if $.Values.niceCXOne.enabled }}
{{- if (not .Values.niceCXOne.oidcClient.existingSecret) }}
  {{- if not (lookup "v1" "Secret" $.Release.Namespace "cognigy-nice-cxone-oidc-client") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cognigy-nice-cxone-oidc-client
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  client-id: "{{ .Values.niceCXOne.oidcClient.clientId | default "" | b64enc }}"
  client-secret: "{{ .Values.niceCXOne.oidcClient.clientSecret | default "" | b64enc }}"
  {{- end }}
{{- end }}
{{- end }}
