{{- if (not .Values.commonSecrets.cognigyAuthJwt.existingSecret) }}
  {{- if not (lookup "v1" "Secret" $.Release.Namespace "cognigy-auth-jwt") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cognigy-auth-jwt
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  # use 128 bytes of random value, hex
  secret: "{{ .Values.commonSecrets.cognigyAuthJwt.token | default (printf "%x" (randAlphaNum 128)) | b64enc }}"
  {{- end }}
{{- end }}