{{- if .Values.ingress.enabled }}
{{- range $mfeConfig := (include "mfe.list" $ | fromJson).items }}
{{- if and $mfeConfig.values $mfeConfig.values.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $mfeConfig.name }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    owner-team: {{ $mfeConfig.team }}
  annotations:
    {{- if $.Values.tls.enabled }}
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    {{- else }}
    traefik.ingress.kubernetes.io/router.entrypoints: web
    {{- end }}
    {{- $middlewares := printf "%s-strip-mfe-%s@kubernetescrd" $.Release.Namespace $mfeConfig.pathName }}
    {{- if $.Values.ingress.serviceUi.ipWhiteListMiddleware.enabled }}
    {{- $middlewares = printf "%s,%s-ipwhitelistserviceui@kubernetescrd" $middlewares $.Release.Namespace }}
    {{- end }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ $middlewares }}
spec:
  ingressClassName: traefik
  {{- include "tlsCertificate.secretName.render" $ | nindent 2 }}
  rules:
  - host: {{ $.Values.ingress.serviceUi.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ $mfeConfig.name }}
            port:
              number: 80
        path: /microfrontends/{{ $mfeConfig.pathName }}
        pathType: Prefix
{{- end }}
{{- end }}
{{- end }}
