{{ if not (lookup "v1" "Secret" $.Release.Namespace "cognigy-service-endpoint-api-access-token") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cognigy-service-endpoint-api-access-token
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  # use 16 bytes of random value, hex
  api-access-token: "{{ printf "%x" (randAlphaNum 16) | b64enc }}"
{{- end }}