{{- if .Values.serviceSentinel.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: ops-center-kube-prom-crd-config
  namespace: {{ $.Release.Namespace | quote }}
data:
  kubePromStackCrdConfig.json: |
    {
      "0.74.0": {
        "prometheusRule": {
          "apiVersion": "monitoring.coreos.com/v1",
          "kind": "PrometheusRule",
          "metadata": {
            "name": "${prometheusRuleName}",
            "namespace": "${namespace}"
          },
          "spec": {
            "groups": [
              {
                "name": "cognigy_ai_ops_center_alerts",
                "rules": "${rules}"
              }
            ]
          }
        },
        "alertManagerConfig": {
          "apiVersion": "monitoring.coreos.com/v1alpha1",
          "kind": "AlertmanagerConfig",
          "metadata": {
            "name": "${alertManagerConfigName}",
            "namespace": "${namespace}",
            "labels": {
              "organisation": "${organisationId}",
              "managedBy": "cognigy-ai-ops-center",
              "alertmanagerConfig": "enabled"
            }
          },
          "spec": {
            "route": {
              "routes": [
                {
                  "receiver": "receivers-${organisationId}",
                  "matchers": [
                    {
                      "name": "organisation",
                      "value": "${organisationId}",
                      "isRegex": false
                    },
                    {
                      "name": "managedBy",
                      "value": "cognigy-ai-ops-center",
                      "isRegex": false
                    }
                  ],
                  "groupBy": [
                    "alertname",
                    "organisation",
                    "managedBy"
                  ],
                  "groupWait": "30s",
                  "groupInterval": "15m",
                  "repeatInterval": "4h"
                }
              ],
              "groupBy": [
                "alertname",
                "organisation",
                "managedBy"
              ],
              "groupWait": "30s",
              "groupInterval": "15m",
              "repeatInterval": "4h",
              "receiver": "null"
            },
            "receivers": "${receivers}"
          }
        }
      },
      "0.83.0": {
        "prometheusRule": {
          "apiVersion": "monitoring.coreos.com/v1",
          "kind": "PrometheusRule",
          "metadata": {
            "name": "${prometheusRuleName}",
            "namespace": "${namespace}"
          },
          "spec": {
            "groups": [
              {
                "name": "cognigy_ai_ops_center_alerts",
                "rules": "${rules}"
              }
            ]
          }
        },
        "alertManagerConfig": {
          "apiVersion": "monitoring.coreos.com/v1alpha1",
          "kind": "AlertmanagerConfig",
          "metadata": {
            "name": "${alertManagerConfigName}",
            "namespace": "${namespace}",
            "labels": {
              "organisation": "${organisationId}",
              "managedBy": "cognigy-ai-ops-center",
              "alertmanagerConfig": "enabled"
            }
          },
          "spec": {
            "route": {
              "routes": [
                {
                  "receiver": "receivers-${organisationId}",
                  "matchers": [
                    {
                      "name": "organisation",
                      "value": "${organisationId}",
                      "matchType": "="
                    },
                    {
                      "name": "managedBy",
                      "value": "cognigy-ai-ops-center",
                      "matchType": "="
                    }
                  ],
                  "groupBy": [
                    "alertname",
                    "organisation",
                    "managedBy"
                  ],
                  "groupWait": "30s",
                  "groupInterval": "15m",
                  "repeatInterval": "4h"
                }
              ],
              "groupBy": [
                "alertname",
                "organisation",
                "managedBy"
              ],
              "groupWait": "30s",
              "groupInterval": "15m",
              "repeatInterval": "4h",
              "receiver": "null"
            },
            "receivers": "${receivers}"
          }
        }
      }
    }

{{- end}}