{{- if .Values.serviceSentinel.enabled }}
{{- if (not .Values.commonSecrets.opsCenterInternalApiSecret.existingSecret) }}
  {{- if not (lookup "v1" "Secret" $.Release.Namespace "ops-center-internal-api-secret") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ops-center-internal-api-secret
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  # use 128 bytes of random value, hex
  secret: "{{ .Values.commonSecrets.opsCenterInternalApiSecret.token | default (printf "%x" (randAlphaNum 128)) | b64enc }}"
  {{- end }}
{{- end }}
{{- end }}