{{- if .Values.serviceSentinel.enabled }}
## Service Account for Service Sentinel
## To be used by the Service Sentinel to create PrometheusRules
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-sentinel
  namespace: {{ $.Release.Namespace | quote }}
{{- end }}