{{- if .Values.serviceSentinel.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: ai-ops-center-webhook-secret
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
{{- end }}